repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        entry: flakeheaven lint
        language: system
        types: [python]
        files: firepred/
